import type { Metadata } from "next"
import { createClient } from "@/lib/supabase/server"
import { ArrowLeft } from "lucide-react"
import Link from "next/link"
import { HistoryList } from "@/components/dashboard/HistoryList"

export const metadata: Metadata = {
  title: "History — DomainForge",
  description: "Your domain search and action history.",
}

// mock history and timeAgo moved to HistoryList

const MOCK_HISTORY = [
  { id: "h1", type: "saved",    domain: "forge.ai",      ts: "2026-06-27T08:32:00Z", note: "Saved to watchlist" },
  { id: "h2", type: "checked",  domain: "nexus.io",      ts: "2026-06-26T15:10:00Z", note: "Availability checked — Taken" },
  { id: "h3", type: "removed",  domain: "buildflow.io",  ts: "2026-06-25T11:30:00Z", note: "Removed from watchlist" },
  { id: "h4", type: "generated",domain: "brewly.ai",     ts: "2026-06-24T09:00:00Z", note: "Generated by AI engine" },
  { id: "h5", type: "checked",  domain: "quantum.dev",   ts: "2026-06-23T14:20:00Z", note: "Availability confirmed — Available" },
  { id: "h6", type: "saved",    domain: "cortex.app",    ts: "2026-06-22T16:45:00Z", note: "Saved to watchlist" },
  { id: "h7", type: "generated",domain: "vaultkey.com",  ts: "2026-06-21T10:15:00Z", note: "Generated by AI engine" },
  { id: "h8", type: "removed",  domain: "stacklane.io",  ts: "2026-06-20T08:00:00Z", note: "Removed from watchlist" },
  { id: "h9", type: "checked",  domain: "domain.cloud",  ts: "2026-06-19T13:30:00Z", note: "Checked — Premium domain" },
  { id: "h10",type: "saved",    domain: "domain.cloud",  ts: "2026-06-18T17:00:00Z", note: "Saved to watchlist" },
]

export default async function HistoryPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  // Fetch real watchlist entries as proxy for history
  const { data: watchlist } = await supabase
    .from("watchlist")
    .select("id, domain, status, created_at")
    .eq("user_id", user!.id)
    .order("created_at", { ascending: false })
    .limit(20)

  // Merge real data with mock history
  const realEvents = (watchlist ?? []).map((w, i) => ({
    id: `real-${w.id}`,
    type: "saved" as const,
    domain: w.domain as string,
    ts: w.created_at as string,
    note: `Saved to watchlist — ${w.status}`,
  }))

  const allEvents = [...realEvents, ...MOCK_HISTORY]
    .sort((a, b) => new Date(b.ts).getTime() - new Date(a.ts).getTime())
    .slice(0, 30)

  return (
    <div className="px-6 py-8 max-w-[1400px] mx-auto">
      <div className="mb-2">
        <Link
          href="/dashboard"
          className="inline-flex items-center gap-1.5 text-sm text-zinc-500 hover:text-zinc-300 transition-colors duration-150 mb-3"
        >
          <ArrowLeft className="h-4 w-4" strokeWidth={1.5} />
          Back to dashboard
        </Link>
        <h1 className="text-xl font-semibold text-zinc-100">History</h1>
        <p className="text-sm text-zinc-500 mt-0.5">
          Your domain search and action log
        </p>
      </div>

      <HistoryList initialEvents={allEvents} />
    </div>
  )
}
