import type {
  WatchlistItem,
  DashboardStats,
  ActivityEvent,
  AvailabilityTrend,
  ScoreDistribution,
} from "@/types/dashboard"

// ─── Mock Watchlist Items ─────────────────────────────────────────────────────

export const MOCK_WATCHLIST: WatchlistItem[] = [
  {
    id: "1",
    domain: "forge.ai",
    status: "available",
    score: 94,
    tags: ["brandable", "ai", "premium"],
    notes: "Perfect for AI tooling startup. Short, punchy.",
    createdAt: "2026-06-20T10:00:00Z",
    expiresAt: "2026-07-05T10:00:00Z",
    priceEstimate: "$2,499",
    priceHistory: [1800, 2000, 2100, 2300, 2499],
    socialX: "forgeai",
    socialIg: "forge.ai",
    socialXAvailable: true,
    socialIgAvailable: false,
    alert_enabled: true,
    notify_frequency: "immediate",
    notification_preferences: { availability: true, price_drop: true, expiration: true },
    checkingNow: false,
  },
  {
    id: "2",
    domain: "nexus.io",
    status: "taken",
    score: 88,
    tags: ["compound", "tech"],
    notes: "Competitor registered last month. Watch for expiry.",
    createdAt: "2026-06-18T09:30:00Z",
    expiresAt: "2026-08-18T09:30:00Z",
    priceEstimate: "$890",
    priceHistory: [700, 750, 800, 850, 890],
    socialX: "nexusio",
    socialIg: "nexus.io",
    socialXAvailable: false,
    socialIgAvailable: false,
    alert_enabled: true,
    notify_frequency: "immediate",
    notification_preferences: { availability: true, price_drop: true, expiration: true },
    checkingNow: false,
  },
  {
    id: "3",
    domain: "quantum.dev",
    status: "available",
    score: 81,
    tags: ["technical", "dev", "keyword"],
    notes: null,
    createdAt: "2026-06-22T14:15:00Z",
    expiresAt: "2026-07-22T14:15:00Z",
    priceEstimate: "$340",
    priceHistory: [280, 295, 310, 325, 340],
    socialX: "quantumdev",
    socialIg: "quantum.dev",
    socialXAvailable: true,
    socialIgAvailable: true,
    alert_enabled: true,
    notify_frequency: "immediate",
    notification_preferences: { availability: true, price_drop: true, expiration: true },
    checkingNow: false,
  },
  {
    id: "4",
    domain: "domain.cloud",
    status: "premium",
    score: 76,
    tags: ["cloud", "enterprise"],
    notes: "High price. Evaluate quarterly.",
    createdAt: "2026-06-15T11:45:00Z",
    expiresAt: null,
    priceEstimate: "$12,000",
    priceHistory: [10000, 11000, 11500, 12000, 12000],
    socialX: null,
    socialIg: null,
    socialXAvailable: null,
    socialIgAvailable: null,
    alert_enabled: true,
    notify_frequency: "immediate",
    notification_preferences: { availability: true, price_drop: true, expiration: true },
    checkingNow: false,
  },
  {
    id: "5",
    domain: "brewly.ai",
    status: "available",
    score: 91,
    tags: ["brandable", "ai", "client-alpha"],
    notes: "Client Alpha's top pick. Register ASAP.",
    createdAt: "2026-06-25T08:00:00Z",
    expiresAt: "2026-07-10T08:00:00Z",
    priceEstimate: "$59",
    priceHistory: [45, 50, 52, 55, 59],
    socialX: "brewlyai",
    socialIg: "brewlyai",
    socialXAvailable: true,
    socialIgAvailable: true,
    alert_enabled: true,
    notify_frequency: "immediate",
    notification_preferences: { availability: true, price_drop: true, expiration: true },
    checkingNow: false,
  },
  {
    id: "6",
    domain: "stacklane.io",
    status: "taken",
    score: 72,
    tags: ["compound", "saas"],
    notes: null,
    createdAt: "2026-06-10T17:20:00Z",
    expiresAt: "2026-09-10T17:20:00Z",
    priceEstimate: "$280",
    priceHistory: [240, 250, 260, 270, 280],
    socialX: "stacklane",
    socialIg: null,
    socialXAvailable: false,
    socialIgAvailable: null,
    alert_enabled: true,
    notify_frequency: "immediate",
    notification_preferences: { availability: true, price_drop: true, expiration: true },
    checkingNow: false,
  },
  {
    id: "7",
    domain: "cortex.app",
    status: "available",
    score: 85,
    tags: ["brandable", "app", "memorable"],
    notes: "Backup option for client B.",
    createdAt: "2026-06-24T13:00:00Z",
    expiresAt: "2026-07-24T13:00:00Z",
    priceEstimate: "$1,200",
    priceHistory: [900, 1000, 1050, 1150, 1200],
    socialX: "cortexapp",
    socialIg: "cortexapp",
    socialXAvailable: true,
    socialIgAvailable: false,
    alert_enabled: true,
    notify_frequency: "immediate",
    notification_preferences: { availability: true, price_drop: true, expiration: true },
    checkingNow: false,
  },
  {
    id: "8",
    domain: "vaultkey.com",
    status: "checking",
    score: 79,
    tags: ["security", "fintech"],
    notes: "Checking availability now...",
    createdAt: "2026-06-27T09:00:00Z",
    expiresAt: null,
    priceEstimate: null,
    priceHistory: [],
    socialX: "vaultkey",
    socialIg: null,
    socialXAvailable: null,
    socialIgAvailable: null,
    alert_enabled: true,
    notify_frequency: "immediate",
    notification_preferences: { availability: true, price_drop: true, expiration: true },
    checkingNow: true,
  },
]

// ─── Mock Stats ───────────────────────────────────────────────────────────────

export const MOCK_STATS: DashboardStats = {
  totalDomains: 24,
  availableNow: 8,
  inWatchlist: 12,
  avgScore: 83,
  totalDelta: +4,
  availableDelta: +2,
}

// ─── Mock Activity ────────────────────────────────────────────────────────────

export const MOCK_ACTIVITY: ActivityEvent[] = [
  {
    id: "a1",
    type: "status_changed",
    domain: "forge.ai",
    message: "Status changed to available",
    timestamp: "2026-06-27T08:32:00Z",
    meta: { fromStatus: "checking", toStatus: "available" },
  },
  {
    id: "a2",
    type: "domain_saved",
    domain: "brewly.ai",
    message: "Saved to watchlist",
    timestamp: "2026-06-25T08:00:00Z",
  },
  {
    id: "a3",
    type: "price_changed",
    domain: "domain.cloud",
    message: "Price updated",
    timestamp: "2026-06-24T16:15:00Z",
    meta: { oldPrice: "$11,000", newPrice: "$12,000" },
  },
  {
    id: "a4",
    type: "check_completed",
    domain: "quantum.dev",
    message: "Availability confirmed",
    timestamp: "2026-06-22T14:20:00Z",
  },
  {
    id: "a5",
    type: "domain_generated",
    domain: "cortex.app",
    message: "Generated via AI engine",
    timestamp: "2026-06-21T10:45:00Z",
  },
  {
    id: "a6",
    type: "domain_removed",
    domain: "buildflow.io",
    message: "Removed from watchlist",
    timestamp: "2026-06-19T15:30:00Z",
  },
  {
    id: "a7",
    type: "status_changed",
    domain: "nexus.io",
    message: "Status changed to taken",
    timestamp: "2026-06-18T09:35:00Z",
    meta: { fromStatus: "available", toStatus: "taken" },
  },
]

// ─── Mock Insights ────────────────────────────────────────────────────────────

export const MOCK_TREND: AvailabilityTrend[] = [
  { date: "Jun 21", available: 5, taken: 7 },
  { date: "Jun 22", available: 6, taken: 6 },
  { date: "Jun 23", available: 7, taken: 5 },
  { date: "Jun 24", available: 6, taken: 6 },
  { date: "Jun 25", available: 8, taken: 4 },
  { date: "Jun 26", available: 7, taken: 5 },
  { date: "Jun 27", available: 8, taken: 4 },
]

export const MOCK_SCORE_DIST: ScoreDistribution[] = [
  { range: "60–69", count: 2 },
  { range: "70–79", count: 4 },
  { range: "80–89", count: 6 },
  { range: "90–100", count: 4 },
]
